server:
  port: 9011
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url: #eureka客户端通过这个地址和eureka服务端进行通讯
      defalutZone: http://127.0.0.1:6768/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-base: #从这里开始写的就是微服务的名字
      path: /base/** #配置请求的规则，这里用到的路径是该服务下的控制层下的路径
      serviceId: tensquare-base #注册到Eureka服务的Id