spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qpaizmzh/tensquare-config.git
  rabbitmq:
    host: 192.168.175.128
server:
  port: 12000
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
