server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.175.128:3306/tensquare_qa?characterEncoding=UTF8&useSSL=false
    username: root
    password: itcast
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: michael jordan
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6768/eureka/
  instance:
    prefer-ip-address: true #适用于方便调试，不加只能本地调试，不能服务器调试？？
